#!/usr/bin/env python
# coding: utf-8
# TEAM: Simon Chiu, Gilbert Lei, Fan Wu, Linyang Yu
# DATE: Jun 26, 2019
#
# PURPOSE: This script is used to clean all files that generated by both Train.py
#          and Prediction.py. Be careful to use this script as it will delete all files.
#          No changes for the empty folder.

# Packages
import os, shutil

# Create path to each folder
report = 'Training_report/'
model = 'Models/'
prediction = 'Prediction/'
img = 'Training_report/img/'
rubric = 'Training_report/rubric/'

# Remove Training Report
for filename in os.listdir(report):
    if filename.endswith(".pdf"): #check any pdf file in the report folder
        file_path = os.path.join(report, filename)
        try:
            os.remove(file_path)
        except:
            print('Cannot remove the file:', file_path)

# Remove Model
for filename in os.listdir(model):
    if filename.endswith(".sav"): #check any sav file in the model folder
        file_path = os.path.join(model, filename)
        try:
            os.remove(file_path)
        except:
            print('Cannot remove the file:', file_path)

# Remove Prediction
for filename in os.listdir(prediction):
    if filename.endswith(".csv"): #check any csv file in the prediction folder
        file_path = os.path.join(prediction, filename)
        try:
            os.remove(file_path)
        except:
            print('Cannot remove the file:', file_path)

# Remove Image
for filename in os.listdir(img):
    if filename.endswith(".png"): #check any png file in the image folder
        file_path = os.path.join(img, filename)
        try:
            os.remove(file_path)
        except:
            print('Cannot remove the file:', file_path)

# Remove Rubric
for filename in os.listdir(rubric):
    if filename.endswith(".csv"): #check any csv file in the rubric folder
        file_path = os.path.join(rubric, filename)
        try:
            os.remove(file_path)
        except:
            print('Cannot remove the file:', file_path)
